function(setup_common_vars HEADERS SOURCES CPPPATH)
    set(${HEADERS}
        ${CPPPATH}/AuthenticationController.h
        ${CPPPATH}/BasemapGalleryController.h
        ${CPPPATH}/BasemapGalleryItem.h
        ${CPPPATH}/BookmarksViewController.h
        ${CPPPATH}/BookmarkListItem.h
        ${CPPPATH}/CoordinateConversionConstants.h
        ${CPPPATH}/CoordinateConversionController.h
        ${CPPPATH}/CoordinateConversionOption.h
        ${CPPPATH}/CoordinateConversionResult.h
        ${CPPPATH}/CoordinateOptionDefaults.h
        ${CPPPATH}/FloorFilterController.h
        ${CPPPATH}/FloorFilterFacilityItem.h
        ${CPPPATH}/FloorFilterLevelItem.h
        ${CPPPATH}/FloorFilterSiteItem.h
        ${CPPPATH}/LocatorSearchSource.h
        ${CPPPATH}/Internal/BasemapGalleryImageProvider.h
        ${CPPPATH}/Internal/GenericListModel.h
        ${CPPPATH}/Internal/GenericTableProxyModel.h
        ${CPPPATH}/Internal/MetaElement.h
        ${CPPPATH}/NorthArrowController.h
        ${CPPPATH}/OverviewMapController.h
        ${CPPPATH}/PopupViewController.h
        ${CPPPATH}/ScalebarController.h
        ${CPPPATH}/SearchResult.h
        ${CPPPATH}/SearchSourceInterface.h
        ${CPPPATH}/SearchSuggestion.h
        ${CPPPATH}/SearchViewController.h
        ${CPPPATH}/SmartLocatorSearchSource.h
        ${CPPPATH}/TimeSliderController.h
        ${CPPPATH}/UtilityNetworkFunctionTraceResult.h
        ${CPPPATH}/UtilityNetworkFunctionTraceResultsModel.h
        ${CPPPATH}/UtilityNetworkListItem.h
        ${CPPPATH}/UtilityNetworkTraceController.h
        ${CPPPATH}/UtilityNetworkTraceStartingPoint.h
        ${CPPPATH}/UtilityNetworkTraceStartingPointsModel.h
        PARENT_SCOPE)

    set(${SOURCES}
        ${CPPPATH}/AuthenticationController.cpp
        ${CPPPATH}/BasemapGalleryController.cpp
        ${CPPPATH}/BasemapGalleryItem.cpp
        ${CPPPATH}/BookmarksViewController.cpp
        ${CPPPATH}/BookmarkListItem.cpp
        ${CPPPATH}/CoordinateConversionConstants.cpp
        ${CPPPATH}/CoordinateConversionController.cpp
        ${CPPPATH}/CoordinateConversionOption.cpp
        ${CPPPATH}/CoordinateConversionResult.cpp
        ${CPPPATH}/CoordinateOptionDefaults.cpp
        ${CPPPATH}/FloorFilterController.cpp
        ${CPPPATH}/FloorFilterFacilityItem.cpp
        ${CPPPATH}/FloorFilterLevelItem.cpp
        ${CPPPATH}/FloorFilterSiteItem.cpp
        ${CPPPATH}/LocatorSearchSource.cpp
        ${CPPPATH}/Internal/BasemapGalleryImageProvider.cpp
        ${CPPPATH}/Internal/GenericListModel.cpp
        ${CPPPATH}/Internal/GenericTableProxyModel.cpp
        ${CPPPATH}/Internal/MetaElement.cpp
        ${CPPPATH}/NorthArrowController.cpp
        ${CPPPATH}/OverviewMapController.cpp
        ${CPPPATH}/PopupViewController.cpp
        ${CPPPATH}/ScalebarController.cpp
        ${CPPPATH}/SearchResult.cpp
        ${CPPPATH}/SearchSourceInterface.cpp
        ${CPPPATH}/SearchSuggestion.cpp
        ${CPPPATH}/SearchViewController.cpp
        ${CPPPATH}/SmartLocatorSearchSource.cpp
        ${CPPPATH}/TimeSliderController.cpp
        ${CPPPATH}/UtilityNetworkFunctionTraceResult.cpp
        ${CPPPATH}/UtilityNetworkFunctionTraceResultsModel.cpp
        ${CPPPATH}/UtilityNetworkListItem.cpp
        ${CPPPATH}/UtilityNetworkTraceController.cpp
        ${CPPPATH}/UtilityNetworkTraceStartingPoint.cpp
        ${CPPPATH}/UtilityNetworkTraceStartingPointsModel.cpp
        PARENT_SCOPE)
endfunction()
